server:
  port: 8081
  tomcat:
    max-http-header-size: 8900
spring:
  application:
    name: serviceDemo1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: info
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8089/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找