server:
  port: 8081
spring:
  application:
    name: serviceDemo1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: debug
